#BoxLayoutExample:
#GridLayoutExample:
TextInputExample:

<TextInputExample>:
    search_input : search_box
    orientation: "vertical"
    BoxLayout:
        height: "40dp" 
        size_hint_y: None
        TextInput:
            id: search_box
            size_hint_x: 50 
        Button:
            text: "Search"
            size_hint_x: 25 
            on_press: root.search_location()
        Label:
            text: ""
            size_hint_x: 25
    Button:
        text:"heLLO"
